service: tasks-api


provider:
  name: aws
  runtime: nodejs8.10
  environment:
    USERS_TABLE: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  
resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: taskId
            AttributeType: S
        KeySchema:
          -
            AttributeName: taskId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

functions:
  getTasks:
    handler: functions/get-tasks.getTasks
    events:
      - http:
          path: api/v1/tasks
          method: GET
          cors: true
  createTask:
    handler: functions/create-task.createTask
    events:
      - http:
          path: api/v1/tasks
          method: POST
          cors: true
  updateTask:
    handler: functions/update-task.updateTask
    events:
      - http:
          path: api/v1/tasks
          method: PUT
          cors: true
  deleteTask:
    handler: functions/delete-task.deleteTask
    events:
      - http:
          path: api/v1/tasks/{taskId}
          method: DELETE
          cors: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'users-tasks-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
